"""Add user_id to Piece.

Revision ID: 1af2d63b2556
Revises: 72a853d46e6
Create Date: 2015-07-28 17:36:38.127480

"""

# revision identifiers, used by Alembic.
revision = '1af2d63b2556'
down_revision = '72a853d46e6'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('piece', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'piece', 'user', ['user_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'piece', type_='foreignkey')
    op.drop_column('piece', 'user_id')
    ### end Alembic commands ###
